// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvXV8wWee9qfbMQKUayrqfAkXz-B6rOE',
    appId: '1:1074110143327:web:b90cbb61a4522d68e134ea',
    messagingSenderId: '1074110143327',
    projectId: 'travel-app-c2105',
    authDomain: 'travel-app-c2105.firebaseapp.com',
    databaseURL: 'https://travel-app-c2105-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-c2105.appspot.com',
    measurementId: 'G-4YZ71XBYP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7qAhNop90AnQtxS2njuhbZ8peJeipSk',
    appId: '1:1074110143327:android:368f14432e670401e134ea',
    messagingSenderId: '1074110143327',
    projectId: 'travel-app-c2105',
    databaseURL: 'https://travel-app-c2105-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-c2105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD000rMxlvn6WjrPOacoiWjf7bjY8PH-_A',
    appId: '1:1074110143327:ios:8e464b1e3e67efa3e134ea',
    messagingSenderId: '1074110143327',
    projectId: 'travel-app-c2105',
    databaseURL: 'https://travel-app-c2105-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-c2105.appspot.com',
    iosBundleId: 'com.example.travelBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD000rMxlvn6WjrPOacoiWjf7bjY8PH-_A',
    appId: '1:1074110143327:ios:5b61a606f230efc1e134ea',
    messagingSenderId: '1074110143327',
    projectId: 'travel-app-c2105',
    databaseURL: 'https://travel-app-c2105-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-c2105.appspot.com',
    iosBundleId: 'com.example.travelBackend.RunnerTests',
  );
}
